# Generated by Django 4.2.4 on 2023-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='persona_name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('System Admin', 'System Admin'), ('Designer', 'Designer'), ('Business Analyst', 'Business Analyst'), ('Project Manager', 'Project Manager'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('Data Analyst', 'Data Analyst'), ('Network Engineer', 'Network Engineer'), ('Technical Writer', 'Technical Writer'), ('Sales Executive', 'Sales Executive')], max_length=255),
        ),
    ]
