# Generated by Django 4.2.4 on 2023-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_persona_persona_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender_name',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='marital_status_name',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='screeningmode',
            name='mode_name',
            field=models.CharField(choices=[('Phone Interview', 'Phone Interview'), ('In-Person Interview', 'In-Person Interview'), ('Video Interview', 'Video Interview'), ('Technical Test', 'Technical Test'), ('Group Discussion', 'Group Discussion')], max_length=255),
        ),
    ]
