# Generated by Django 4.2.4 on 2023-08-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_candidatedirectory_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedirectory',
            name='reason_for_change',
        ),
        migrations.DeleteModel(
            name='Reasonforchange',
        ),
    ]
