# Generated by Django 4.2.4 on 2023-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_candidatedirectory_reason_for_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedirectory',
            name='reason_for_change',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
